spring:
  application:
    name: Welcome-Api

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: '*'
